#!/bin/bash

function run() {
    path="$1"
    shift
    echo "Testing $path"
    out=$(cx -q "$path" "$@")
    #echo $out
    if [ x"$out" != x"OK" ]; then 
        echo FAIL
        exit 1
    fi
}

function expect_failure() {
    path="$1"
    echo "Testing $path"
    cx -q "$path" 2>/dev/null
    if [ $? -eq 0 ]; then 
        echo FAIL
        exit 1
    fi
}

function run_all() {
    run cpp_single_source
    run c_single_source
    run c_many_sources
    run cpp_multiunit/prog
    run cpp_multiunit_2/prog
    run cpp_weird_inc
    run c_math
    run c_socket
    run c_2_programs/main1.c
    run c_cpp_mix
    run cpp_threads
    run cpp_z
    run cpp_deep_1/progs/prog1.cpp
    run c_def
    run cpp_def
    run cpp_args OK
    CX_CONFIG=release run config_1/progs/prog1 release
    CX_CONFIG=debug   run config_1/progs/prog1 debug

    expect_failure c_missing_header
    expect_failure invalid_opt_1
    expect_failure invalid_opt_2
    expect_failure invalid_opt_3
    expect_failure invalid_opt_4
    expect_failure invalid_opt_5
}

#./build

if [ -z `which cx` ]; then
    echo No 'cx' on PATH
    exit 1
fi

# Internal tests.
cx --sanity

# In clean state.
cx --clean .
run_all

# Again, in fresh state.
run_all

