#!/bin/bash

function run() {
    path="$1"
    echo "Testing $path "
    if [ $clean == yes ]; then
        cx --clean "$path"
    fi
    out=$(cx -q --keep-deps "$path")
    #echo $out
    if [ x"$out" != x"OK" ]; then 
        echo FAIL
        exit 1
    fi
}

function expect_failure() {
    path="$1"
    echo "Testing $path "
    if [ $clean == yes ]; then
        cx --clean "$path"
    fi
    cx -q --keep-deps "$path" 2>/dev/null
    if [ $? -eq 0 ]; then 
        echo FAIL
        exit 1
    fi
}

function run_all() {
    clean=$1
    run cpp_single_source
    run c_single_source
    run c_many_sources
    run cpp_multiunit/prog
    run cpp_multiunit_2/prog
    run cpp_weird_inc
    run c_math
    run c_socket
    run c_2_programs/main1.c
    run c_cpp_mix
    run cpp_threads
    run cpp_z
    run cpp_deep_1/progs/prog1.cpp

    expect_failure c_missing_header
    expect_failure invalid_opt_1
    expect_failure invalid_opt_2
    expect_failure invalid_opt_3
    expect_failure invalid_opt_4
    expect_failure invalid_opt_5
}

#./build
cx --sanity

run_all yes
run_all no

